.Dd June 12, 2025
.Dt FP 1
.Os
.
.Sh NAME
.Nm fp
.Nd interactive file picker
.
.Sh SYNOPSIS
.Nm
.Ar lines
.Ar path
.Op Ar path Op Ar ...
.
.Sh DESCRIPTION
.Nm
searches for file from every
.Ar path .
User can type something
and this will be visible on the screen
as
.Ar lines
amount of results.
As result
.Nm
prints found file.
.Nm
prints all the interactive stuff
into stderr
and the result
into stdout,
so this means
you can easily pipe this program
into another one.
